name: Update release-linux-glibc-x86_64 on version change

on:
  push:
    branches:
      - main
    paths:
      - "backend/consts/version.go"

jobs:
  update-release-linux-glibc-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version: "^1.26.0"
          cache-dependency-path: backend/go.sum
      - name: merge main into release
        run: |
          git remote set-url origin git@github.com:janie314/gnuplex.git
          git config user.name "release workflow"
          git config user.email "x@example.com"
          git checkout release-linux-glibc-x86_64
          git merge main -X theirs --allow-unrelated-histories
      - name: build gnuplex
        run: |
          uv run make.py build
      - name: update release branch
        run: |
          umask 077
          echo "${{ secrets.GNUPLEX_DEPLOY }}" >/tmp/gnuplex-deploy
          version_output=$(./backend/bin/gnuplex -version)
          git add .
          git commit -m "$version_output"
          GIT_SSH_COMMAND="ssh -i /tmp/gnuplex-deploy" git push origin release-linux-glibc-x86_64
          rm /tmp/gnuplex-deploy
